## Numpy

> Powerful Third-party Library

|Library name|Contents|
|:---|:---|
|Numpy|array 컴퓨팅 지원|
|Ipython && Jupyter|과학문서 작성과 연구를 정리|
|Numba|분산컴퓨팅|
|Pandas|데이터 프레임 지원|
|matplotlib && Bokeh|데이터 시각화|
|Scikit-learn && Scikit-Image|기계학습과 이미지 프로세싱 처리|

### Numpy
행렬이나 대규모 다차원 배열을 쉽게 처리

계산 과학 분야의 복잡한 연산을 지원 (Number + Python)

Scipy나 Matplotlib, Pandas 등으로 발전, 더 복잡한 연산을 쉽게 처리 가능하도록 지원함

문자열 처리에 적합하다.

#### 배열 
(= Vectors = Matrixes = Images = Tensors = ConvNets)
1. Numpy -> ndarray class
   
   배열을 이용한 벡터화 연산

   배열에는 모두 동일한 자료형만 저장 가능

   메모리에 연속적으로 저장

   일반적으로 리스트보다 빠른 것으로 간주

   > python list VS ndarray

         python list : 모든 타입 입력 가능 -> list block 크기 불규칙 -> 주소로 원소 배정 -> 느림
         
         ndarray : 한 타입만 입력 가능 -> list block 크기 일정 -> 순차적으로 원소 배정 -> 빠름
   

In [10]:
import numpy as np

# 1d array
ar = np.array([1,2,3,4,5])
print(f"1차원 행렬 : {ar}")
# 2d array
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"2차원 행렬 : \n{ar}")
print(f"행 : {len(ar)}, 열 : {len(ar[0])}") # 행과 열 길이 확인
# 3d array
ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"3차원 행렬 : \n{ar}")
print(f"구성 : {ar.shape}, 차수 : {ar.ndim}") # 행과 열 길이 확인

1차원 행렬 : [1 2 3 4 5]
2차원 행렬 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
행 : 3, 열 : 3
3차원 행렬 : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
구성 : (2, 2, 3), 차수 : 3


In [12]:
# 배열 생성 함수
import numpy as np

arr = np.zeros((3,6))
print(arr)
arr = np.ones((3,6))
print(arr)
arr = np.arange(100, 110)
print(arr)
arr = np.arange(100, 110).reshape(2,5)
print(arr)
np.random.random((2,5,3))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[100 101 102 103 104 105 106 107 108 109]
[[100 101 102 103 104]
 [105 106 107 108 109]]


array([[[0.96195846, 0.86004898, 0.80766773],
        [0.51491994, 0.3099914 , 0.18320863],
        [0.65320074, 0.89096   , 0.85113032],
        [0.49508236, 0.20829937, 0.53112094],
        [0.21269134, 0.97161684, 0.04265348]],

       [[0.53102651, 0.71953291, 0.67961169],
        [0.94675148, 0.82503067, 0.02079841],
        [0.82152627, 0.69050541, 0.5466035 ],
        [0.16993313, 0.62295204, 0.84190079],
        [0.11226008, 0.9609146 , 0.3695011 ]]])

## Transpose
행과 열을 교체

```
ar.T
```

## Slicing
1차원 배열 : 리스트와 동일

N차원 배열 : ','로 구별하여 연결

In [18]:
import numpy as np

arr = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print("원래 array\n", arr)

print("1. \n", arr[0:,1:])
print("2. \n", arr[1:,1:])
print("3. \n", arr[1:2,1:2])

원래 array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1. 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
2. 
 [[ 5  6  7]
 [ 9 10 11]]
3. 
 [[5]]


In [19]:
import numpy as np

arr = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]],[[16,17,18,19],[20,21,22,23]]])
print("원래 array\n", arr)

print("1. \n", arr[1:,1:,:1])
print("2. \n", arr[1:,0:,:3])
print("3. \n", arr[1:3,1:4,1:5])

원래 array
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
1. 
 [[[12]]

 [[20]]]
2. 
 [[[ 8  9 10]
  [12 13 14]]

 [[16 17 18]
  [20 21 22]]]
3. 
 [[[13 14 15]]

 [[21 22 23]]]


### Vectorization operation
사칙연산 모두 가능

논리연산과 비교연산, 지수함수, 로그함수도 지원

In [25]:
# python VS numpy 비교

# python
a =[1,2,3]
b = a*2
print(b)

# np
ar = np.array([1,2,3,4,5])
print(ar * 2)

# python으로 위와 같은 작업하려면
ar_a = [1,2,3,4,5]
ar_b = []
for n in ar_a:
    ar_b.append(n*2)
print(ar_b)

[1, 2, 3, 1, 2, 3]
[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [32]:
import numpy as np

arr_1 = np.array([7,5,9,10])
arr_2 = np.array([4,10,6,2])

print(arr_1*3 + arr_2*3)

arr_1 = np.array([[7, 5, 9, 10], [4, 10, 6, 2]])
arr_2 = np.array([[1, 3, 4, 9], [14, 7, 6, 4]])

opr_result = arr_1 - arr_2
for column in opr_result:
    for item in column:
        print_res = True if item > 0 else False
        print(print_res)


[33 45 45 36]
True
True
True
True
False
True
False
False


### Broadcasting (브로드캐스팅)
행렬끼리 연산할 대 크기가 다른 경우 이를 알아서 확대해주는 기능

### 그 외 유용한 기능들
• min, max, argmin, argmax, sum, mean, median

• axis, sort

• var, std

• exp, sqrt, sin, cos

• dot